### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by jherdman** [simonihmig/ember-native-dom-helpers-codemod#22]
FYI I had to install chalk globally to run this. The following is the error that was raised:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/.npm-global/lib/node_modules/ember-native-dom-helpers-codemod/bin/ember-native-dom-helpers-codemod.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by simonihmig** [comment]
@jherdman thanks for reporting. This should be fixed now, released as 0.1.5!
